package com.mycompany.trabalhodesktop;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class ordemDeServico extends javax.swing.JFrame {

    /**
     * Creates new form ordemDeServico
     */
    private String nomeCompleto;

    DecimalFormat df = new DecimalFormat("#.##");
    public double valorTotalServicos;
    public double valorTotalPecas;
    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultTableModel modelo2 = new DefaultTableModel();
    private int linhaSelecionada = -1;

    public ordemDeServico() {
        initComponents();
        setLocationRelativeTo(null);
        carregaTabela();
        carregaTabelaPecas();
    }

    public void carregaTabela() {
        modelo.addColumn("Serviço");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Valor");
        modelo.addColumn("Valor Total");
        tbServicos.setModel(modelo);
        tbServicos.getColumnModel().getColumn(0).setPreferredWidth(350);
        tbServicos.getColumnModel().getColumn(1).setPreferredWidth(290);
        tbServicos.getColumnModel().getColumn(2).setPreferredWidth(290);
        tbServicos.getColumnModel().getColumn(3).setPreferredWidth(290);
    }

    public void carregaTabelaPecas() {
        modelo2.addColumn("Peça");
        modelo2.addColumn("Quantidade");
        modelo2.addColumn("Valor");
        modelo2.addColumn("Valor Total");
        tbPecas.setModel(modelo2);
        tbPecas.getColumnModel().getColumn(0).setPreferredWidth(350);
        tbPecas.getColumnModel().getColumn(1).setPreferredWidth(290);
        tbPecas.getColumnModel().getColumn(2).setPreferredWidth(290);
        tbPecas.getColumnModel().getColumn(3).setPreferredWidth(290);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfServico = new javax.swing.JTextField();
        tfQuantidade = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btEditarServico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbServicos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbTotalServicos = new javax.swing.JLabel();
        lbTotalPecas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPecas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbTotalValorPecas = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        peca = new javax.swing.JLabel();
        valorPeca = new javax.swing.JLabel();
        quantidadePeca = new javax.swing.JLabel();
        tfPeca = new javax.swing.JTextField();
        tfQuantidadePeca = new javax.swing.JTextField();
        tfValorPeca = new javax.swing.JTextField();
        btSalvarPecas = new javax.swing.JButton();
        btEditarPeca = new javax.swing.JButton();
        btresumo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ordem de Serviço");

        jLabel8.setText("Serviço:");

        jLabel9.setText("Valor: ");

        jLabel10.setText("Quantidade:");

        tfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeActionPerformed(evt);
            }
        });

        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btEditarServico.setText("Editar");
        btEditarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfServico, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditarServico)
                .addGap(18, 18, 18)
                .addComponent(btSalvar)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btEditarServico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbServicos);

        jLabel2.setText("Valor Total Serviços: R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(lbTotalServicos)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbTotalServicos))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        tbPecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbPecas);

        jLabel3.setText("Valor Total Peças:  R$");

        javax.swing.GroupLayout lbTotalPecasLayout = new javax.swing.GroupLayout(lbTotalPecas);
        lbTotalPecas.setLayout(lbTotalPecasLayout);
        lbTotalPecasLayout.setHorizontalGroup(
            lbTotalPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbTotalPecasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbTotalPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lbTotalPecasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(lbTotalValorPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        lbTotalPecasLayout.setVerticalGroup(
            lbTotalPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbTotalPecasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lbTotalPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTotalValorPecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        peca.setText("Peça");

        valorPeca.setText("Valor: ");

        quantidadePeca.setText("Quantidade:");

        tfPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPecaActionPerformed(evt);
            }
        });

        tfQuantidadePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadePecaActionPerformed(evt);
            }
        });

        tfValorPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorPecaActionPerformed(evt);
            }
        });

        btSalvarPecas.setText("Salvar");
        btSalvarPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarPecasActionPerformed(evt);
            }
        });

        btEditarPeca.setText("Editar");
        btEditarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarPecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantidadePeca)
                            .addComponent(valorPeca)
                            .addComponent(peca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfValorPeca)
                            .addComponent(tfQuantidadePeca)
                            .addComponent(tfPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btEditarPeca)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvarPecas)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peca)
                    .addComponent(tfPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorPeca)
                    .addComponent(tfValorPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadePeca)
                    .addComponent(tfQuantidadePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarPecas)
                    .addComponent(btEditarPeca))
                .addContainerGap())
        );

        btresumo.setText("Resumo");
        btresumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTotalPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(419, 419, 419)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btresumo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTotalPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btresumo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String servico = tfServico.getText();
        int quantidade;
        double valor;

        try {
            quantidade = Integer.parseInt(tfQuantidade.getText());
            valor = Double.parseDouble(tfValor.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite valores numéricos válidos para quantidade e valor!");
            return;
        }

        if (!servico.isEmpty() && quantidade > 0 && valor > 0) {
            if (linhaSelecionada >= 0) {
                double totalAntigo = (int) tbServicos.getValueAt(linhaSelecionada, 1) * (double) tbServicos.getValueAt(linhaSelecionada, 2);
                modelo.removeRow(linhaSelecionada);
                modelo.insertRow(linhaSelecionada, new Object[]{servico, quantidade, valor, quantidade * valor});
                valorTotalServicos += (quantidade * valor - totalAntigo);
                JOptionPane.showMessageDialog(this, "Serviço editado com sucesso!");
            } else {
                double total = quantidade * valor;
                modelo.addRow(new Object[]{servico, quantidade, valor, total});
                valorTotalServicos += total;
                JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso!");

            }

            lbTotalServicos.setText(String.valueOf(valorTotalServicos));
            tfServico.setText("");
            tfQuantidade.setText("");
            tfValor.setText("");
            tfServico.requestFocus();
            linhaSelecionada = -1;

        } else {
            JOptionPane.showMessageDialog(this, "Digite um Serviço com nome válido!");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfQuantidadePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadePecaActionPerformed

    private void tfValorPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorPecaActionPerformed

    private void btSalvarPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarPecasActionPerformed
        String peca = tfPeca.getText();
        int quantidade;
        double valor;

        try {
            quantidade = Integer.parseInt(tfQuantidadePeca.getText());
            valor = Double.parseDouble(tfValorPeca.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite valores numéricos válidos para quantidade e valor!");
            return;
        }

        if (!peca.isEmpty() && quantidade > 0 && valor > 0) {
            if (linhaSelecionada >= 0) {
                double totalAntigo = (int) tbPecas.getValueAt(linhaSelecionada, 1) * (double) tbPecas.getValueAt(linhaSelecionada, 2);
                modelo2.removeRow(linhaSelecionada);
                modelo2.insertRow(linhaSelecionada, new Object[]{peca, quantidade, valor, quantidade * valor});
                valorTotalPecas += (quantidade * valor - totalAntigo);
                JOptionPane.showMessageDialog(this, "Peça editada com sucesso!");
            } else {
                double total = quantidade * valor;
                modelo2.addRow(new Object[]{peca, quantidade, valor, total});
                valorTotalPecas += total; 
                JOptionPane.showMessageDialog(this, "Peça cadastrada com sucesso!");

            }

            lbTotalValorPecas.setText(String.valueOf(valorTotalPecas));
            tfPeca.setText("");
            tfQuantidadePeca.setText("");
            tfValorPeca.setText("");
            tfPeca.requestFocus();
            linhaSelecionada = -1;
        } else {
            JOptionPane.showMessageDialog(this, "Digite uma peça com nome válido!");
        }
    }//GEN-LAST:event_btSalvarPecasActionPerformed

    public Object[] getDadosPecaSelecionada() {
        int linhaSelecionada = tbPecas.getSelectedRow();
        if (linhaSelecionada >= 0) {
            Object[] dadosPeca = new Object[3];
            for (int i = 0; i < dadosPeca.length; i++) {
                dadosPeca[i] = modelo2.getValueAt(linhaSelecionada, i);
            }
            return dadosPeca;
        }
        return null;
    }

    public Object[] getDadosServicoSelecionado() {
        int linhaSelecionada = tbServicos.getSelectedRow();
        if (linhaSelecionada >= 0) {
            Object[] dadosServico = new Object[3];
            for (int i = 0; i < dadosServico.length; i++) {
                dadosServico[i] = modelo.getValueAt(linhaSelecionada, i);
            }
            return dadosServico;
        }
        return null;
    }

    private void btresumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresumoActionPerformed

        boolean tabelaPecasPreenchida = tbPecas.getRowCount() > 0;
        boolean tabelaServicosPreenchida = tbServicos.getRowCount() > 0;

        if (tabelaPecasPreenchida || tabelaServicosPreenchida) {
            resumoTotal resumo = new resumoTotal(modelo2, modelo, valorTotalPecas, valorTotalServicos);
            resumo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Adicione pelo menos uma peça ou serviço para prosseguir");
        }
    }//GEN-LAST:event_btresumoActionPerformed

    private void tfPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPecaActionPerformed

    private void btEditarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarPecaActionPerformed
        linhaSelecionada = -1;
        linhaSelecionada = tbPecas.getSelectedRow();

        if (linhaSelecionada >= 0) {
            String peca = (String) tbPecas.getValueAt(linhaSelecionada, 0);
            int quantidade = (int) tbPecas.getValueAt(linhaSelecionada, 1);
            double valor = (double) tbPecas.getValueAt(linhaSelecionada, 2);

            tfPeca.setText(peca);
            tfQuantidadePeca.setText(String.valueOf(quantidade));
            tfValorPeca.setText(String.valueOf(valor));
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma peça na tabela!");
        }
    }//GEN-LAST:event_btEditarPecaActionPerformed

    private void btEditarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarServicoActionPerformed
        linhaSelecionada = -1;
        linhaSelecionada = tbServicos.getSelectedRow();

        if (linhaSelecionada >= 0) {
            String servico = (String) tbServicos.getValueAt(linhaSelecionada, 0);
            int quantidade = (int) tbServicos.getValueAt(linhaSelecionada, 1);
            double valor = (double) tbServicos.getValueAt(linhaSelecionada, 2);

            tfServico.setText(servico);
            tfQuantidade.setText(String.valueOf(quantidade));
            tfValor.setText(String.valueOf(valor));
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um serviço na tabela!");
        }
    }//GEN-LAST:event_btEditarServicoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditarPeca;
    private javax.swing.JButton btEditarServico;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvarPecas;
    private javax.swing.JButton btresumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lbTotalPecas;
    private javax.swing.JLabel lbTotalServicos;
    private javax.swing.JLabel lbTotalValorPecas;
    private javax.swing.JLabel peca;
    private javax.swing.JLabel quantidadePeca;
    private javax.swing.JTable tbPecas;
    private javax.swing.JTable tbServicos;
    private javax.swing.JTextField tfPeca;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfQuantidadePeca;
    private javax.swing.JTextField tfServico;
    private javax.swing.JTextField tfValor;
    private javax.swing.JTextField tfValorPeca;
    private javax.swing.JLabel valorPeca;
    // End of variables declaration//GEN-END:variables
}
